# TCL File Generated by Component Editor 13.0sp1
# Fri Oct 21 19:11:32 BRST 2016
# DO NOT MODIFY

# 
# motors_matrix "motors_matrix" v1.0
#  2016.10.21.19:11:32
# motors_matriz
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module motors_matrix
# 
set_module_property DESCRIPTION motors_matriz
set_module_property NAME motors_matrix
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME motors_matrix
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL matriz_avalon_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file matriz_avalon_interface.vhd VHDL PATH src/matriz_avalon_interface.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter rows POSITIVE 4
set_parameter_property rows DEFAULT_VALUE 4
set_parameter_property rows DISPLAY_NAME rows
set_parameter_property rows TYPE POSITIVE
set_parameter_property rows UNITS None
set_parameter_property rows ALLOWED_RANGES 1:2147483647
set_parameter_property rows HDL_PARAMETER true
add_parameter cols POSITIVE 4
set_parameter_property cols DEFAULT_VALUE 4
set_parameter_property cols DISPLAY_NAME cols
set_parameter_property cols TYPE POSITIVE
set_parameter_property cols UNITS None
set_parameter_property cols ALLOWED_RANGES 1:2147483647
set_parameter_property cols HDL_PARAMETER true
add_parameter data_width POSITIVE 32
set_parameter_property data_width DEFAULT_VALUE 32
set_parameter_property data_width DISPLAY_NAME data_width
set_parameter_property data_width TYPE POSITIVE
set_parameter_property data_width UNITS None
set_parameter_property data_width ALLOWED_RANGES 1:2147483647
set_parameter_property data_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point pwms
# 
add_interface pwms conduit end
set_interface_property pwms associatedClock clock_sink
set_interface_property pwms associatedReset reset_sink
set_interface_property pwms ENABLED true
set_interface_property pwms EXPORT_OF ""
set_interface_property pwms PORT_NAME_MAP ""
set_interface_property pwms SVD_ADDRESS_GROUP ""

add_interface_port pwms coe_pwms_export export Output rows*cols


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink csi_csink_clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rsi_rsink_resetn reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_aslave_write write Input 1
add_interface_port avalon_slave avs_aslave_address address Input 1
add_interface_port avalon_slave avs_aslave_writedata writedata Input data_width
add_interface_port avalon_slave avs_aslave_readdata readdata Output data_width
add_interface_port avalon_slave avs_aslave_read read Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

